class User(object):
    def __init__(self, **data):
        self.Ic_no = data.get('Ic_no', "")
        self.name = data.get('name', "")
        self.age = data.get('age', "")
        self.password = data.get('password', "")
        self.phone_number = data.get('phone_number', "")
        self.occupation = data.get('occupation', "")
        self.vaccination = data.get('vaccination', "")
        self.covid_status = data.get('covid_status', "")
        self.vaccine_status = data.get('vaccine_status', "")
        self.vacc_apt_date1 = data.get('vacc_apt_date1', "")
        self.vacc_apt_date2 = data.get('vacc_apt_date2', "")
        self.vacc_apt_location = data.get('vacc_apt_location', "")
        self.vacc_time = data.get('vacc_time', "")
        self.add = data.get('add', "")
        self.pc = data.get('pc', "")
        self.rsvp = data.get('rsvp', "")
        self.med_history = data.get('med_history', "")
        self.pr = data.get('pr', "")